name: Publish Node Docker
on:
  push:
   branches: [ main ]
  pull_request:
    branches: [ main ]
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build & Push Image
      run: |
        echo "${{ secrets.DOCKERPASSWORD }}" | docker login -u "lalitaly" --password-stdin
        docker image build -t lalitaly/egcogit:latest .
        docker push lalitaly/egcogit:latest
        
